### PR TITLE
testing flask gnmi timeout

### PR DESCRIPTION
**Pull request by hellt**
if you run 
```
docker exec client7 bash /config/install_gnmic.sh
```
in this branch you will see the error

### CODE REVIEW

**Comment by alfilipe** [comment]
The flask app have been changed to fix the issue with unavailable connections, it will try to connect every 10 seconds (the amount of seconds can be changed on the flask app  under the function '__\_\_init\_\___' of the class '__Telemetry__').
The file "install_gnmic.sh" has been changed to allow the flask app stdout and stderr to be writen on the docker logs.

while the nodes are not reachable you will see some messages like those bellow:

```
[Flask] - sub_telemetry - unable to connect to the host pe1 will try agrain in 10 seconds
[Flask] - update_anysec_status - unable to connect to the host pe1 will try agrain in 10 seconds
[Flask] - update_port_status - unable to connect to the host p3 will try agrain in 10 seconds
```

while the node is available and an GNMI connection can be established but the GNMI path is not accessible yet, can be exepted the see some exception errors link the one bellow:

```
Exception in thread Thread-320:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/flask_app/venv/lib/python3.9/site-packages/pygnmi/client.py", line 997, in enqueue_updates
    for update in subscription:
  File "/flask_app/venv/lib/python3.9/site-packages/grpc/_channel.py", line 542, in __next__
    return self._next()
  File "/flask_app/venv/lib/python3.9/site-packages/grpc/_channel.py", line 968, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.CANCELLED
        details = "Channel closed!"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Channel closed!", grpc_status:1, created_time:"2024-03-28T21:47:50.534257369+00:00"}"
```
after that the all will run as it is supposed to be.

**Review by tiago-amado — CHANGES_REQUESTED** [review]
We need to uncomment nodes from yml file. Those were commented only for tests.

**Comment by tiago-amado** [comment]
@alfilipe, we need to merge your code into the main. this branch was created for test proposes and there are changes in the yml file that must be reverted. Either we do that or we create a new clean branch and deploy the changes again.
@hellt, how do you suggest to proceed?

**Comment by hellt** [comment]
@tiago-amado I don't think we need to proceed with this now
The repo works from the main branch, @aaakpinar please confirm if that is the case and you don't have local changes that were not pushed to the repo.

As far as the future state of the automation panel is concerned, @siva19susi is almost done with the refactored versiont that we will use later in favor of the current python version.

**Comment by hellt** [comment]
superseded by #38

**Pull request closed without merging**
